'use strict';

exports.__esModule = true;

var appendStyles = require('append-styles')


appendStyles({
  css: "html{overflow:hidden}.rc4_15_2-ReactStyleguidist-common__font-1g6Es{color:#555;font-family:inherit}.rc4_15_2-ReactStyleguidist-colors__link-1Wsxa,.rc4_15_2-ReactStyleguidist-colors__link-1Wsxa:active,.rc4_15_2-ReactStyleguidist-colors__link-1Wsxa:hover,.rc4_15_2-ReactStyleguidist-colors__link-1Wsxa:link,.rc4_15_2-ReactStyleguidist-colors__link-1Wsxa:visited{color:#30aabc}.rc4_15_2-ReactStyleguidist-colors__link-1Wsxa:focus{-webkit-transition:none;transition:none;opacity:1;outline:0;text-decoration:underline}.rc4_15_2-ReactStyleguidist-colors__link-1Wsxa:active{text-decoration:none}.rc4_15_2-ReactStyleguidist-ComponentsList__heading-3K8b-{font-weight:600}.rc4_15_2-ReactStyleguidist-ComponentsList__item-IgR86{margin:0;overflow:hidden;text-overflow:ellipsis;line-height:1.78571;letter-spacing:.04em;color:#777;font-size:14px;font-weight:300}.rc4_15_2-ReactStyleguidist-ComponentsList__link-1zfFY,.rc4_15_2-ReactStyleguidist-ComponentsList__link-1zfFY:active,.rc4_15_2-ReactStyleguidist-ComponentsList__link-1zfFY:hover,.rc4_15_2-ReactStyleguidist-ComponentsList__link-1zfFY:link,.rc4_15_2-ReactStyleguidist-ComponentsList__link-1zfFY:visited{color:inherit}.rc4_15_2-ReactStyleguidist-ComponentsList__list-j3Cak{padding-top:10px;padding-left:20px}.rc4_15_2-ReactStyleguidist-Playground__root-3P8LG{overflow:visible}.rc4_15_2-ReactStyleguidist-ReactComponent__primaryHeading-1nzbq{line-height:1.78571;letter-spacing:.04em;font-size:25px}.rc4_15_2-ReactStyleguidist-Section__heading-3Qf0F{line-height:1.11111;letter-spacing:1.9px;color:#30aabc;font-size:36px;font-weight:400}.rc4_15_2-ReactStyleguidist-StyleGuide__content-1GMJs{margin:0;min-width:640px}.rc4_15_2-ReactStyleguidist-StyleGuide__footer-2ZRbu{display:none}.rc4_15_2-ReactStyleguidist-StyleGuide__heading-IUff9{display:none}.rc4_15_2-ReactStyleguidist-StyleGuide__sidebar-15dHV{left:300px;background-color:inherit;width:210px;overflow-x:hidden}.rc4_15_2-ReactStyleguidist-TableOfContents__search-3Wuqr:focus{border-color:#30aabc}.rc4_15_2-ReactStyleguidist-Markdown__pre-1rkm2{margin-bottom:20px}",
  id: 'rc-styles',
  before: 'ssc-styles'
})

exports.default = {"ReactStyleguidist-common__font":"rc4_15_2-ReactStyleguidist-common__font-1g6Es","ReactStyleguidist-colors__link":"rc4_15_2-ReactStyleguidist-colors__link-1Wsxa","ReactStyleguidist-ComponentsList__heading":"rc4_15_2-ReactStyleguidist-ComponentsList__heading-3K8b-","ReactStyleguidist-ComponentsList__item":"rc4_15_2-ReactStyleguidist-ComponentsList__item-IgR86","ReactStyleguidist-ComponentsList__link":"rc4_15_2-ReactStyleguidist-ComponentsList__link-1zfFY","ReactStyleguidist-ComponentsList__list":"rc4_15_2-ReactStyleguidist-ComponentsList__list-j3Cak","ReactStyleguidist-Playground__root":"rc4_15_2-ReactStyleguidist-Playground__root-3P8LG","ReactStyleguidist-ReactComponent__primaryHeading":"rc4_15_2-ReactStyleguidist-ReactComponent__primaryHeading-1nzbq","ReactStyleguidist-Section__heading":"rc4_15_2-ReactStyleguidist-Section__heading-3Qf0F","ReactStyleguidist-StyleGuide__content":"rc4_15_2-ReactStyleguidist-StyleGuide__content-1GMJs","ReactStyleguidist-StyleGuide__footer":"rc4_15_2-ReactStyleguidist-StyleGuide__footer-2ZRbu","ReactStyleguidist-StyleGuide__heading":"rc4_15_2-ReactStyleguidist-StyleGuide__heading-IUff9","ReactStyleguidist-StyleGuide__sidebar":"rc4_15_2-ReactStyleguidist-StyleGuide__sidebar-15dHV","ReactStyleguidist-TableOfContents__search":"rc4_15_2-ReactStyleguidist-TableOfContents__search-3Wuqr","ReactStyleguidist-Markdown__pre":"rc4_15_2-ReactStyleguidist-Markdown__pre-1rkm2"}
