name: CI

on:
  pull_request:

  push:
    branches:
      - main
      - next

permissions:
  contents: read

jobs:
  initialize:
    runs-on: ubuntu-latest
    outputs:
      teams: ${{ steps.get-teams.outputs.teams }}
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: pnpm

      - run: pnpm install
      - id: get-teams
        run: echo "teams=$(pnpm garden github-teams --user ${{ github.triggering_actor }} --token $GH_TOKEN)" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - run: pnpm build
      - uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: dist

  lint:
    needs: [initialize]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: pnpm

      - run: pnpm install
      - run: pnpm lint:ci

  test:
    needs: [initialize]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: pnpm

      - run: pnpm install
      - uses: actions/download-artifact@v4
        with:
          name: dist-artifact
          path: packages

      - run: pnpm test run --coverage --coverage.reporter lcov
      - uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
        with:
          file: .cache/coverage/lcov.info

  deploy-staging:
    if: >
      github.ref != 'refs/heads/main' &&
      (contains(needs.initialize.outputs.teams, 'Writers') ||
       github.actor == 'dependabot[bot]' ||
       github.actor == 'renovate[bot]')
    needs: [initialize]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: pnpm

      - run: pnpm install
      - run: pnpm build:demo
      - run: scripts/deploy.mjs
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  deploy:
    if: > # temporarily disable to preserve v9 storybook demo
      false &&
      contains(needs.initialize.outputs.teams, 'Writers') && (github.ref == 'refs/heads/main')
    needs: [initialize, lint, test]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: 'gh-pages'
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: pnpm

      - run: pnpm install
      - run: pnpm build:demo
      - run: mv .cache/coverage .cache/demo
      - run: scripts/deploy.mjs
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  publish:
    needs: [initialize, lint, test]
    runs-on: ubuntu-latest
    if: contains(needs.initialize.outputs.teams, 'Maintainers') && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/next')
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Lerna requires the full history, including tags

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: pnpm
          registry-url: https://registry.npmjs.org # Sets the registry in the project level .npmrc

      - run: pnpm install

      - uses: actions/download-artifact@v4
        with:
          name: dist-artifact
          path: packages

      - run: pnpm lerna publish from-git --ignore-scripts --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
